/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLLER.CidadeController;
import MODEL.Cidade;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PC13
 */
public class telaCadCidade extends javax.swing.JFrame {

    CidadeController controller;
    Cidade cid;

    public telaCadCidade() {
        initComponents();
        controller = new CidadeController();
        //telacadfuncionario telafuncionario
    }
    
    // telaInternalframe cadCida = new telaInternalgrame ();
    // cadCid.setvisible(true);
    //cadcid.movetofront();
    //cadcida.setareatrabalho(this.getareatrabalho());
    //gettelaprincipal().centralizarfrom(cadcid);
    //getareatrabaalho.add(cadCid);
    //this.dispose();

    public Cidade criarObjeto() {
        cid = new Cidade();

        cid.setNome(JTFCidade.getText());
        cid.setUf(JCBUf.getSelectedItem().toString());
        cid.setPais(JTFPais.getText());
        if (JTFCodigo.getText().equals("")) {

        } else {
            cid.setCodigo(Integer.parseInt(JTFCodigo.getText()));
        }
        return cid;
    }
    public void habilitarCampus(int btn){
        switch (btn){
            case 1://Pesquisar
                JBNovo.setEnabled(false);
                JBAlterar.setEnabled(true);
                JBExcluir.setEnabled(true);
                JBCancelar.setEnabled(true);
                JBSalvar.setEnabled(false);
                JTFCidade.setEnabled(true);
                JTFPais.setEnabled(true);
                JCBUf.setEnabled(true);
                JBanterior.setEnabled(true);
                JBprimeiro.setEnabled(true);
                JBproximo.setEnabled(true);
                JBultimo.setEnabled(true);
                break;
            case 2://novo
                JBNovo.setEnabled(false);
                JBAlterar.setEnabled(false);
                JBExcluir.setEnabled(false);
                JBCancelar.setEnabled(true);
                JBSalvar.setEnabled(true);
                JTFCidade.setEnabled(true);
                JTFPais.setEnabled(true);
                JCBUf.setEnabled(true);
                JBanterior.setEnabled(false);
                JBprimeiro.setEnabled(false);
                JBproximo.setEnabled(false);
                JBultimo.setEnabled(false);
                JBPesquisar.setEnabled(false);
                JTFPesquisar.setEnabled(false);
               break;
            case 3: //salvar, excluir, alterar
               JBPesquisar.setEnabled(true);
               JTFPesquisar.setEnabled(true);
               JTFCidade.setEnabled(false);
               JCBUf.setEnabled(false);
               JTFPais.setEnabled(false);
               JBNovo.setEnabled(true);
               JBSalvar.setEnabled(false);
               JBAlterar.setEnabled(false);
               JBExcluir.setEnabled(false);
               JBCancelar.setEnabled(false);
               JBanterior.setEnabled(false);
               JBprimeiro.setEnabled(false);
               JBproximo.setEnabled(false);
               JBultimo.setEnabled(false);
            break;
            default:
                break;
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        JTFPesquisar = new javax.swing.JTextField();
        JBPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JBultimo = new javax.swing.JButton();
        JBanterior = new javax.swing.JButton();
        JBproximo = new javax.swing.JButton();
        JBprimeiro = new javax.swing.JButton();
        JBNovo = new javax.swing.JButton();
        JBSalvar = new javax.swing.JButton();
        JBAlterar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JTFCodigo = new javax.swing.JTextField();
        JTFCidade = new javax.swing.JTextField();
        JCBUf = new javax.swing.JComboBox<>();
        JTFPais = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cidade");

        jLabel2.setText("Pesquisar:");

        JTFPesquisar.setText("Digite o código ou nome da cidade");
        JTFPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFPesquisarMouseClicked(evt);
            }
        });
        JTFPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPesquisarActionPerformed(evt);
            }
        });
        JTFPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFPesquisarKeyPressed(evt);
            }
        });

        JBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Pesquisar.png"))); // NOI18N
        JBPesquisar.setText("Pesquisar");
        JBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText("Código");

        jLabel4.setText("Cidade");

        jLabel5.setText("Estado");

        jLabel6.setText("País");

        JBultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Ultimo.png"))); // NOI18N
        JBultimo.setEnabled(false);

        JBanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Anterior.png"))); // NOI18N
        JBanterior.setEnabled(false);

        JBproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Proximo.png"))); // NOI18N
        JBproximo.setEnabled(false);

        JBprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/primeiro.png"))); // NOI18N
        JBprimeiro.setEnabled(false);

        JBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/novo.png"))); // NOI18N
        JBNovo.setText("Novo");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/gravar.png"))); // NOI18N
        JBSalvar.setText("Salvar");
        JBSalvar.setEnabled(false);
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/alterar.png"))); // NOI18N
        JBAlterar.setText("Alterar");
        JBAlterar.setEnabled(false);
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });

        JBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/excluir.png"))); // NOI18N
        JBExcluir.setText("Excluir");
        JBExcluir.setEnabled(false);
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        JBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/cancelar.png"))); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.setEnabled(false);
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JTFCodigo.setEnabled(false);

        JTFCidade.setEnabled(false);
        JTFCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFCidadeMouseClicked(evt);
            }
        });
        JTFCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFCidadeKeyPressed(evt);
            }
        });

        JCBUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        JTFPais.setEnabled(false);
        JTFPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFPaisMouseClicked(evt);
            }
        });
        JTFPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBUf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFPais))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFCidade))))
                .addGap(18, 18, 18))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBNovo)
                .addGap(18, 18, 18)
                .addComponent(JBSalvar)
                .addGap(18, 18, 18)
                .addComponent(JBAlterar)
                .addGap(18, 18, 18)
                .addComponent(JBExcluir)
                .addGap(18, 18, 18)
                .addComponent(JBCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBPesquisar)
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPesquisar))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JCBUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JTFPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBultimo)
                    .addComponent(JBproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBprimeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBNovo)
                    .addComponent(JBSalvar)
                    .addComponent(JBCancelar)
                    .addComponent(JBAlterar)
                    .addComponent(JBExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPesquisarActionPerformed
        pesquisar();
      
    }//GEN-LAST:event_JBPesquisarActionPerformed

    private void JTFPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPesquisarActionPerformed

    private void JTFPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPaisActionPerformed

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        
        habilitarCampus(2);
        limparCampus();
        JTFCodigo.setText(Integer.toString(controller.pegarIdCidade()+1));
    }//GEN-LAST:event_JBNovoActionPerformed

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        if (verificarCampus()) {
        controller.cadastrar(this.criarObjeto());
        this.limparCampus();
        this.habilitarCampus(3);
        }
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
       int opcao = JOptionPane.showConfirmDialog(null,"Deseja realmente excluir a Funcionário?","Mensagem do Sistema",JOptionPane.INFORMATION_MESSAGE);
       if(opcao == 0){
           controller.deletar(this.criarObjeto());
           this.habilitarCampus(3);
           this.limparCampus();
       }
    }//GEN-LAST:event_JBExcluirActionPerformed

    private void JTFPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFPesquisarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.pesquisar();
        }
    }//GEN-LAST:event_JTFPesquisarKeyPressed

    private void JTFPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFPesquisarMouseClicked
        JTFPesquisar.setText("");
    }//GEN-LAST:event_JTFPesquisarMouseClicked

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        int opcao =JOptionPane.showConfirmDialog(null,"Deseja realmente atualizar os dados da cidade","Mensagem do Sistema",JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
        if (opcao == 0) {
            if(verificarCampus()){
            controller.alterar(this.criarObjeto());
            limparCampus();
            habilitarCampus(3);
            }  
        }
    }//GEN-LAST:event_JBAlterarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.habilitarCampus(3);
        this.limparCampus();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTFCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCidadeKeyPressed
        
    }//GEN-LAST:event_JTFCidadeKeyPressed

    private void JTFCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFCidadeMouseClicked
        JTFCidade.setBackground(Color.white);
        JTFCidade.setText("");
    }//GEN-LAST:event_JTFCidadeMouseClicked

    private void JTFPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFPaisMouseClicked
       JTFPais.setBackground(Color.white);
        JTFPais.setText("");
    }//GEN-LAST:event_JTFPaisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadCidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JButton JBanterior;
    private javax.swing.JButton JBprimeiro;
    private javax.swing.JButton JBproximo;
    private javax.swing.JButton JBultimo;
    private javax.swing.JComboBox<String> JCBUf;
    private javax.swing.JTextField JTFCidade;
    private javax.swing.JTextField JTFCodigo;
    private javax.swing.JTextField JTFPais;
    private javax.swing.JTextField JTFPesquisar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void pesquisar() {
        cid = controller.pesquisar(JTFPesquisar.getText());
        if (cid.getCodigo() == 0) {
            this.habilitarCampus(3);
            JOptionPane.showMessageDialog(null, "Cidade não encontrada","Mensagem do Sistema",JOptionPane.INFORMATION_MESSAGE);         
        } else {
            JTFCodigo.setText(Integer.toString(cid.getCodigo()));
            JTFCidade.setText(cid.getNome());
            JTFPais.setText(cid.getPais());
            JCBUf.setSelectedItem(cid.getUf());
            habilitarCampus(1);
        }
    }

    private void limparCampus() {
       JTFCidade.setText("");
       JTFCodigo.setText("");
       JTFPais.setText("");
       JTFPesquisar.setText("Digite o código ou nome da Cidade");
       JCBUf.setSelectedIndex(0);
    }
    
    public boolean verificarCampus(){
        boolean preechido = true;
        if (JTFCidade.getText().isEmpty()){
            JTFCidade.setText("O campo nome não pode ficar vazio");
            JTFCidade.setBackground(Color.red);
            preechido = false;
        }
        if (JTFPais.getText().isEmpty()) {
            JTFPais.setText("O campo País não pode ficar vazio");
            JTFPais.setBackground(Color.red);
            preechido = false;
            
        }
        return preechido;
    }
}
