/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLLER.MarcaController;
import CONTROLLER.ProdutoController;
//import CONTROLLER.ProdutoController;
import CONTROLLER.TipoController;
import MODEL.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC13
 */
public class TelaTabelaProduto extends javax.swing.JInternalFrame {

   // ProdutoController controller;
    Produto prod;
    DefaultTableModel TbProdutos;
    TelaCadProduto cadProd;
    ArrayList<Produto> produtos;
    MarcaController ControllerMarca;
    TipoController ControllerTipo;
    ProdutoController controllerProduto;
    

    /**
     * Creates new form TelaTabelaProduto
     */
    public TelaTabelaProduto() {
        initComponents();
//        controller = new ProdutoController();
        TbProdutos = (DefaultTableModel) JTProduto.getModel();
        
        ControllerTipo = new TipoController();
        ControllerMarca = new MarcaController();
        controllerProduto = new ProdutoController();
        prod  =new Produto();
        produtos = new ArrayList<>();
        this.listarProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFPesquisar = new javax.swing.JTextField();
        JBPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTProduto = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        JBNovo = new javax.swing.JButton();
        JBAlterar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Produto");

        jLabel1.setText("Pesquisar");

        JTFPesquisar.setText("Digite o código ou nome do Produto");
        JTFPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPesquisarActionPerformed(evt);
            }
        });

        JBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Pesquisar.png"))); // NOI18N
        JBPesquisar.setText("Pesquisar");
        JBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPesquisarActionPerformed(evt);
            }
        });

        JTProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Produto", "Modelo", "Marca", "Tipo", "Data Vencimento", "Descrição", "Percentual Venda ", "Peso", "Unidade Compra", "Unidade venda", "Valor de Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTProduto);

        JBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/novo.png"))); // NOI18N
        JBNovo.setText("Novo");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        JBAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/alterar.png"))); // NOI18N
        JBAlterar.setText("Alterar");
        JBAlterar.setEnabled(false);
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });

        JBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/excluir.png"))); // NOI18N
        JBExcluir.setText("Excluir");
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        JBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/cancelar.png"))); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.setEnabled(false);
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTFPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(JBPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBNovo)
                        .addGap(123, 123, 123)
                        .addComponent(JBAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(JBExcluir)
                        .addGap(123, 123, 123)
                        .addComponent(JBCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPesquisar))
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBNovo)
                    .addComponent(JBCancelar)
                    .addComponent(JBExcluir)
                    .addComponent(JBAlterar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        TelaCadProduto cadProd = new TelaCadProduto();
        cadProd.show();


    }//GEN-LAST:event_JBNovoActionPerformed

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente artualizar os dados da produto", "Mensagem do sistema", JOptionPane.INFORMATION_MESSAGE);
        if (opcao == 0) {
           controllerProduto.alterar(this.criarObjeto());
            limparCampo();
            habilitarCampos(3);
        }
    }//GEN-LAST:event_JBAlterarActionPerformed

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a Produto?", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        if (opcao == 0) {
            controllerProduto.deletar(this.criarObjeto());
            TbProdutos.removeRow(JTProduto.getSelectedRow());
        }


    }//GEN-LAST:event_JBExcluirActionPerformed
    public Produto criarObjeto() {
        prod = new Produto();
        prod = controllerProduto.pesquisar(Integer.parseInt(JTProduto.getValueAt(JTProduto.getSelectedRow(), 0).toString()));
        prod.setNomeProduto(String.valueOf(JTProduto.getValueAt(JTProduto.getSelectedRow(), 1)));
        prod.setModeloProduto(String.valueOf(JTProduto.getValueAt(JTProduto.getSelectedRow(), 2)));
        prod.setDataVencimentoProduto(String.valueOf(JTProduto.getValueAt(JTProduto.getSelectedRow(), 5)));
        prod.setDescricaoProduto(String.valueOf(JTProduto.getValueAt(JTProduto.getSelectedRow(), 6)));
        prod.setPercetualProduto(Double.parseDouble(JTProduto.getValueAt(JTProduto.getSelectedRow(), 7).toString()));
        prod.setPesoProduto(Double.parseDouble(JTProduto.getValueAt(JTProduto.getSelectedRow(), 8).toString()));
        prod.setUnidCompraProduto(String.valueOf(JTProduto.getValueAt(JTProduto.getSelectedRow(), 9)));
        prod.setUnidVendaProduto(String.valueOf(JTProduto.getValueAt(JTProduto.getSelectedRow(), 10)));
        prod.setValorVendaProduto(Double.parseDouble(JTProduto.getValueAt(JTProduto.getSelectedRow(), 11).toString()));
        return prod;
    }
    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.listarProduto();
        this.habilitarCampos(2);
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTFPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPesquisarActionPerformed

    private void JBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPesquisarActionPerformed
        this.pesquisar();        // TODO add your handling code here:
    }//GEN-LAST:event_JBPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JTextField JTFPesquisar;
    private javax.swing.JTable JTProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void listarProduto() {
        produtos = controllerProduto.selecionarProdutos();
        this.removerLinha();
        for (Produto prod : produtos) {
            TbProdutos.addRow(new Object[]{
                prod.getIdProduto(),
                prod.getNomeProduto(),
                prod.getModeloProduto(),
                ControllerMarca.pesquisar(prod.getIdMarcaProduto()).getNomeMarca(),
                ControllerTipo.pesquisar(prod.getIdTipoProduto()).getNomeTipo(),
                prod.getDataVencimentoProduto(),
                prod.getDescricaoProduto(),
                prod.getPercetualProduto(),
                prod.getPesoProduto(),
                prod.getUnidCompraProduto(),
                prod.getUnidVendaProduto(),
                prod.getValorVendaProduto(),    
                
            });
        }
    }

    ;

    private void removerLinha() {
        int linhas = TbProdutos.getRowCount();
        for (int i = linhas - 1; i >= 0; i--) {
            TbProdutos.removeRow(i);
        }
    }

    public void pesquisar() {
        produtos = controllerProduto.pesquisarProdutos(JTFPesquisar.getText());
        if (produtos.isEmpty()) {
            this.limparCampo();
            this.habilitarCampos(3);
            JOptionPane.showMessageDialog(null, "Produto não encontrada", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            this.removerLinha();
            for (Produto prod : produtos) {
                TbProdutos.addRow(new Object[]{ prod.getIdProduto(),
                prod.getNomeProduto(),
                prod.getModeloProduto(),
                ControllerMarca.pesquisar(prod.getIdMarcaProduto()).getNomeMarca(),
                ControllerTipo.pesquisar(prod.getIdTipoProduto()).getNomeTipo(),
                prod.getDataVencimentoProduto(),
                prod.getDescricaoProduto(),
                prod.getPercetualProduto(),
                prod.getPesoProduto(),
                prod.getUnidCompraProduto(),
                prod.getUnidVendaProduto(),
                prod.getValorVendaProduto()});
            }
            this.habilitarCampos(1);
        }
    }

    private void limparCampo() {
        JTFPesquisar.setText("");
    }

    private void habilitarCampos(int i) {
        switch (i) {
            case 1://Pesquisar
                JBNovo.setEnabled(false);
                JBAlterar.setEnabled(true);
                JBExcluir.setEnabled(true);
                JBCancelar.setEnabled(true);
                break;
            case 2://novo
                JBNovo.setEnabled(true);
                JBAlterar.setEnabled(false);
                JBExcluir.setEnabled(false);
                JBCancelar.setEnabled(false);
                JBPesquisar.setEnabled(true);
                JTFPesquisar.setEnabled(true);
                break;
            case 3: //salvar, excluir, alterar
                JBPesquisar.setEnabled(true);
                JTFPesquisar.setEnabled(true);
                JBNovo.setEnabled(true);
                JBAlterar.setEnabled(false);
                JBExcluir.setEnabled(false);
                JBCancelar.setEnabled(false);
                break;
            default:
                break;

        }
    }
}
